export const ActionTypes = {
    GET_PERSONS: "GET_PERSONS",
    GET_CAROUSEL_ITEMS: "GET_CAROUSEL_ITEMS",
    GET_PRODUCTS: "GET_PRODUCTS",
    SEND_CONTACT_FORM: "SEND_CONTACT_FORM",
    SEND_PRODUCT_FORM: "SEND_PRODUCT_FORM",
};