export const ActionTypes = {
    GET_PERSONS: "GET_PERSONS",
    GET_CAROUSEL_ITEMS: "GET_CAROUSEL_ITEMS",
    GET_PRODUCTS: "GET_PRODUCTS",
    SEND_CONTACT_FORM: "SEND_CONTACT_FORM",
    SEND_PRODUCT_FORM: "SEND_PRODUCT_FORM",
    SEND_REGISTRATION_FORM: "SEND_REGISTRATION_FORM",
    SEND_LOGIN_FORM: "SEND_LOGIN_FORM",
    CLEAR_LOGIN_STATUS: "CLEAR_LOGIN_STATUS",
    LOGOUT_USER: "LOGOUT_USER",
    SEND_ORDER_FORM: "SEND_ORDER_FORM",
    GET_MY_ORDERS: "GET_MY_ORDERS",
    GET_PRODUCT: "GET_PRODUCT",
    GET_ALL_ORDERS: "GET_ALL_ORDERS",
    SEND_PAYMENT_DONE: "SEND_PAYMENT_DONE",
    SEND_STATUS_CHANGE: "SEND_STATUS_CHANGE",
    CLEAR_STATUS_PAYMENT_DONE: "CLEAR_STATUS_PAYMENT_DONE",
    
};